 
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quienparecequien;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class GameScreenn extends javax.swing.JFrame {

    /**
     * Creates new form GameScreen
     */
    //Creamos las variables que vamos a usar en el constructor de la clase GameScreen
    //que son los puntos, el array de personajes y el numero del personaje ganador que lo creo como constante para que no sea alterado por ningun metodo ni nada.
    private int punto=0;
    private Personaje listaPers[]= new Personaje[12];
    private final int persGanador = (int)(Math.random()*12);
    private ArrayList<Users> listaUsers= new ArrayList<Users>();
    
    public GameScreenn() throws IOException, FileNotFoundException, ClassNotFoundException {
       //Creamos un file con el archivo para comprobar si existe si y con el if le decimos si existe carga el archivo, si no existe creame esta lista.
        File pers = new File("listaPers.dat");
        if(!pers.exists()){
            listaPers[0]=new Personaje("Alejandro", true, true, false, true, false, true, 0);
            listaPers[1]=new Personaje("Kiko", true, false, true, true, false, true, 1);
            listaPers[2]=new Personaje("Javi", true, true, false, true, true, true, 2);
            listaPers[3]=new Personaje("Pepe", false, true, true, true, true, false, 3);
            listaPers[4]=new Personaje("Maria", false, false, false, false, false, true, 4);
            listaPers[5]=new Personaje("Isabel", true, false, false, false, false, true, 5);
            listaPers[6]=new Personaje("Cristina", false,false, false, false, false, false, 6);
            listaPers[7]=new Personaje("Susana", false, true, false, false, false, false, 7);
            listaPers[8]=new Personaje("Alfredo", true, false, false, true, true, true, 8);
            listaPers[9]=new Personaje("Alvaro", false, true, true, true, true, true, 9);
            listaPers[10]=new Personaje("Antonio", true, false, true, true, true, true, 10);
            listaPers[11]=new Personaje("Jose", false, false, true, true, true, false, 11);
            Personaje.serializarPersonajes("listaPers.dat", listaPers);
        } else
            //Con este metodo de la clase Personaje obtenemos los personajes anteriormente serializados y los introducimos en un array;
            Personaje.obtenerPersonajes("listaPers.dat", listaPers);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGPreguntas = new javax.swing.ButtonGroup();
        PanlePrincipal = new javax.swing.JPanel();
        jPanelJuego = new javax.swing.JPanel();
        jPanelPersonajes = new javax.swing.JPanel();
        jCBAlejandro = new javax.swing.JCheckBox();
        JCBKiko = new javax.swing.JCheckBox();
        JCBJavi = new javax.swing.JCheckBox();
        JCBPepe = new javax.swing.JCheckBox();
        JCBMaria = new javax.swing.JCheckBox();
        JCBIsabel = new javax.swing.JCheckBox();
        JCBCristina = new javax.swing.JCheckBox();
        JCBSusana = new javax.swing.JCheckBox();
        JCBAlfredo = new javax.swing.JCheckBox();
        JCBAlvaro = new javax.swing.JCheckBox();
        JCBAntonio = new javax.swing.JCheckBox();
        JCBJose = new javax.swing.JCheckBox();
        jPanelDerecha = new javax.swing.JPanel();
        jPanelPreguntas = new javax.swing.JPanel();
        jRNarizon = new javax.swing.JRadioButton();
        jRCalvo = new javax.swing.JRadioButton();
        jRHombre = new javax.swing.JRadioButton();
        jRBlanco = new javax.swing.JRadioButton();
        jRBigote = new javax.swing.JRadioButton();
        jRSombrero = new javax.swing.JRadioButton();
        jPanelBotonesAccion = new javax.swing.JPanel();
        jBPreguntar = new javax.swing.JButton();
        jBResolver = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanelInformacion = new javax.swing.JPanel();
        jLInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMINuvaPartida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelJuego.setLayout(new java.awt.BorderLayout());

        jPanelPersonajes.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPersonajes.setLayout(new java.awt.GridLayout(3, 4));

        jCBAlejandro.setForeground(new java.awt.Color(255, 255, 255));
        jCBAlejandro.setText("0.Alejandro");
        jCBAlejandro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Alejandro.jpg"))); // NOI18N
        jCBAlejandro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/AlejandroTachado.jpg"))); // NOI18N
        jCBAlejandro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBAlejandroMouseClicked(evt);
            }
        });
        jCBAlejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlejandroActionPerformed(evt);
            }
        });
        jPanelPersonajes.add(jCBAlejandro);

        JCBKiko.setForeground(new java.awt.Color(255, 255, 255));
        JCBKiko.setText("1.Kiko");
        JCBKiko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Kiko.jpg"))); // NOI18N
        JCBKiko.setIconTextGap(1);
        JCBKiko.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/KikoTachado.jpg"))); // NOI18N
        JCBKiko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBKikoMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBKiko);

        JCBJavi.setForeground(new java.awt.Color(255, 255, 255));
        JCBJavi.setText("2.Javi");
        JCBJavi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Javi.jpg"))); // NOI18N
        JCBJavi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/JaviTachado.jpg"))); // NOI18N
        JCBJavi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBJaviMouseClicked(evt);
            }
        });
        JCBJavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBJaviActionPerformed(evt);
            }
        });
        jPanelPersonajes.add(JCBJavi);

        JCBPepe.setForeground(new java.awt.Color(255, 255, 255));
        JCBPepe.setText("3.Pepe");
        JCBPepe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Pepe.jpg"))); // NOI18N
        JCBPepe.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/PepeTachado.jpg"))); // NOI18N
        JCBPepe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBPepeMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBPepe);

        JCBMaria.setForeground(new java.awt.Color(255, 255, 255));
        JCBMaria.setText("4.Maria");
        JCBMaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Maria.jpg"))); // NOI18N
        JCBMaria.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/MariaTachado.jpg"))); // NOI18N
        JCBMaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBMariaMouseClicked(evt);
            }
        });
        JCBMaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBMariaActionPerformed(evt);
            }
        });
        jPanelPersonajes.add(JCBMaria);

        JCBIsabel.setForeground(new java.awt.Color(255, 255, 255));
        JCBIsabel.setText("5.Isabel");
        JCBIsabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Isabel.jpg"))); // NOI18N
        JCBIsabel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/IsabelTachado.jpg"))); // NOI18N
        JCBIsabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBIsabelMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBIsabel);

        JCBCristina.setForeground(new java.awt.Color(255, 255, 255));
        JCBCristina.setText("6.Cristina");
        JCBCristina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Cristina.jpg"))); // NOI18N
        JCBCristina.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/CristinaTachado.jpg"))); // NOI18N
        JCBCristina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBCristinaMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBCristina);

        JCBSusana.setForeground(new java.awt.Color(255, 255, 255));
        JCBSusana.setText("7.Susana");
        JCBSusana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Susana.jpg"))); // NOI18N
        JCBSusana.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/SusanaTachado.jpg"))); // NOI18N
        JCBSusana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBSusanaMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBSusana);

        JCBAlfredo.setForeground(new java.awt.Color(255, 255, 255));
        JCBAlfredo.setText("8.Alfredo");
        JCBAlfredo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Alfredo.jpg"))); // NOI18N
        JCBAlfredo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/AlfredoTachado.jpg"))); // NOI18N
        JCBAlfredo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBAlfredoMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBAlfredo);

        JCBAlvaro.setForeground(new java.awt.Color(255, 255, 255));
        JCBAlvaro.setText("9.Alvaro");
        JCBAlvaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Alvaro.jpg"))); // NOI18N
        JCBAlvaro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/AlvaroTachado.jpg"))); // NOI18N
        JCBAlvaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBAlvaroMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBAlvaro);

        JCBAntonio.setForeground(new java.awt.Color(255, 255, 255));
        JCBAntonio.setText("10.Antonio");
        JCBAntonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Antonio.jpg"))); // NOI18N
        JCBAntonio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/AntonioTachado.jpg"))); // NOI18N
        JCBAntonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBAntonioMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBAntonio);

        JCBJose.setForeground(new java.awt.Color(255, 255, 255));
        JCBJose.setText("11.Jose");
        JCBJose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/Jose.jpg"))); // NOI18N
        JCBJose.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/quienparecequien/IMG/JoseTachado.jpg"))); // NOI18N
        JCBJose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBJoseMouseClicked(evt);
            }
        });
        jPanelPersonajes.add(JCBJose);

        jPanelJuego.add(jPanelPersonajes, java.awt.BorderLayout.CENTER);

        jPanelDerecha.setLayout(new java.awt.BorderLayout());

        jPanelPreguntas.setBackground(new java.awt.Color(0, 153, 153));
        jPanelPreguntas.setLayout(new java.awt.GridLayout(6, 0));

        BGPreguntas.add(jRNarizon);
        jRNarizon.setForeground(new java.awt.Color(0, 0, 0));
        jRNarizon.setText("Tiene gafas?");
        jPanelPreguntas.add(jRNarizon);

        BGPreguntas.add(jRCalvo);
        jRCalvo.setForeground(new java.awt.Color(0, 0, 0));
        jRCalvo.setText("Tiene pelo?");
        jPanelPreguntas.add(jRCalvo);

        BGPreguntas.add(jRHombre);
        jRHombre.setForeground(new java.awt.Color(0, 0, 0));
        jRHombre.setText("Es hombre?");
        jPanelPreguntas.add(jRHombre);

        BGPreguntas.add(jRBlanco);
        jRBlanco.setForeground(new java.awt.Color(0, 0, 0));
        jRBlanco.setText("Es blanco?");
        jPanelPreguntas.add(jRBlanco);

        BGPreguntas.add(jRBigote);
        jRBigote.setForeground(new java.awt.Color(0, 0, 0));
        jRBigote.setText("Tiene bigote?");
        jPanelPreguntas.add(jRBigote);

        BGPreguntas.add(jRSombrero);
        jRSombrero.setForeground(new java.awt.Color(0, 0, 0));
        jRSombrero.setText("Tiene sombrero?");
        jPanelPreguntas.add(jRSombrero);

        jPanelDerecha.add(jPanelPreguntas, java.awt.BorderLayout.CENTER);

        jPanelBotonesAccion.setBackground(new java.awt.Color(0, 204, 204));
        jPanelBotonesAccion.setLayout(new java.awt.BorderLayout());

        jBPreguntar.setBackground(new java.awt.Color(0, 255, 204));
        jBPreguntar.setForeground(new java.awt.Color(0, 0, 0));
        jBPreguntar.setText("Preguntar");
        jBPreguntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreguntarActionPerformed(evt);
            }
        });
        jPanelBotonesAccion.add(jBPreguntar, java.awt.BorderLayout.CENTER);

        jBResolver.setBackground(new java.awt.Color(255, 255, 0));
        jBResolver.setForeground(new java.awt.Color(0, 0, 0));
        jBResolver.setText("Resolver");
        jBResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResolverActionPerformed(evt);
            }
        });
        jPanelBotonesAccion.add(jBResolver, java.awt.BorderLayout.LINE_START);

        jBSalir.setBackground(new java.awt.Color(255, 0, 51));
        jBSalir.setForeground(new java.awt.Color(0, 0, 0));
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanelBotonesAccion.add(jBSalir, java.awt.BorderLayout.SOUTH);

        jPanelDerecha.add(jPanelBotonesAccion, java.awt.BorderLayout.PAGE_END);

        jPanelJuego.add(jPanelDerecha, java.awt.BorderLayout.EAST);

        jPanelInformacion.setBackground(new java.awt.Color(0, 0, 0));
        jPanelInformacion.setLayout(new java.awt.BorderLayout());

        jLInfo.setBackground(new java.awt.Color(0, 0, 0));
        jLInfo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInfo.setText("Que pregunta tienes?");
        jLInfo.setToolTipText("");
        jPanelInformacion.add(jLInfo, java.awt.BorderLayout.PAGE_END);

        jPanelJuego.add(jPanelInformacion, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout PanlePrincipalLayout = new javax.swing.GroupLayout(PanlePrincipal);
        PanlePrincipal.setLayout(PanlePrincipalLayout);
        PanlePrincipalLayout.setHorizontalGroup(
            PanlePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
        );
        PanlePrincipalLayout.setVerticalGroup(
            PanlePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanlePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMINuvaPartida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMINuvaPartida.setText("Nueva Partida");
        jMINuvaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINuvaPartidaActionPerformed(evt);
            }
        });
        jMenu1.add(jMINuvaPartida);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanlePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanlePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//boton para salir
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed
//Boton de pregunta
    private void jBPreguntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPreguntarActionPerformed
       //Si la pregunta esta seleccionada primero suma un punto
        if(jRNarizon.isSelected()){
            punto++;
            //A continuacion comprueba con el indice del personaje ganador si tiene o no lo que le han preguntado y lo respendo mediante el Jlabel
            if(listaPers[persGanador].isGafas())
                jLInfo.setText("El personaje tiene gafas");
            else
                jLInfo.setText("El personaje no tiene gafas");
        }
        else if(jRCalvo.isSelected()){
            punto++;
            if(listaPers[persGanador].isPelo())
                jLInfo.setText("El personaje es calvo");
            else
                jLInfo.setText("El personaje tiene pelo");
        }
        else if(jRBigote.isSelected()){
            punto++;
            if(listaPers[persGanador].isBigote())
                jLInfo.setText("El personaje tiene bigote");
            else
                jLInfo.setText("El personaje no tiene bigote");
        }
        else if(jRBlanco.isSelected()){
            punto++;
            if(listaPers[persGanador].isBlanco())
                jLInfo.setText("El personaje es blanco");
            else
                jLInfo.setText("El personaje es moreno");
        }
        else if(jRSombrero.isSelected()){
            punto++;
            if(listaPers[persGanador].isSombrero())
                jLInfo.setText("El personaje tiene sombrero");
            else
                jLInfo.setText("El personaje no tiene sombrero");
        }
        else if(jRHombre.isSelected()){
            punto++;
            if(listaPers[persGanador].isHombre())
                jLInfo.setText("El personaje es Hombre");
            else
                jLInfo.setText("El personaje es Mujer");
        }
    }//GEN-LAST:event_jBPreguntarActionPerformed
//Boton de resolver
    private void jBResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResolverActionPerformed
        //Creamos una variable para introducir el numero que teclea el usuario en el JOP.
        //Creamos un try dentro de un while para que solo pueda introducir numeros en el mensaje de respuessta si introduce otro simbolo el juego te dice que no has 
        //introducido un dato valido y vuelves a intentarlo.
      boolean bien=false;
      int userResuelve=0;
        while(!bien){
        try{ 
        userResuelve = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el numero del personaje elejido"));
        bien=true;
       }catch(NumberFormatException e){
           jLInfo.setText("Porfavor, introduce un numero valido");
           bien=false;
       }}
       //En este condicional si acierta sale este mensaje y a continuacion le pide mideante un JOP que diga su nombre
        if(persGanador==userResuelve){
            jLInfo.setText("Enhorabuena as acertado el personaje oculto");
            String nombreUser= JOptionPane.showInputDialog("Escribe tu nombre");
           //Aqui si hace un try para guardar los datos del usuario con los respectivos puntos que ha echo, creando un objeto tipo Users y guardandolo en un archivo.
           File antiguosUser = new File("listaUsuarios.dat");
           
           
           
           if(antiguosUser.exists()){
                try {
                    Users.obtenerUser("listaUsuarios.dat", listaUsers);
                } catch (IOException ex) {
                    Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaUsers.add(new Users(nombreUser, punto));
                    try {
                        Users.serializarUser("listaUsuarios.dat", listaUsers );
                    } catch (IOException ex) {
                        Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "No se puede guardar la puntuacion", ex);
                    }}
           else{
               listaUsers.add(new Users(nombreUser, punto));
                    try {
                        Users.serializarUser("listaUsuarios.dat", listaUsers );
                    } catch (IOException ex) {
                        Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "No se puede guardar la puntuacion", ex);
                    }
           }


            //Y por ultimo crea la nueva pantalla para mostrar la tabla de puntos y oculta esta.
            this.setVisible(false);
            PantallaPuntuacion pPuntos = null;
            try {
                pPuntos = new PantallaPuntuacion();
            } catch (IOException ex) {
                Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "IOex", ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "Clase ex", ex);
            }
            pPuntos.setVisible(true);
        }else{//Si falla se le suma otro punto y se sigue jugando.
            punto++;
            jLInfo.setText("Has fallado, vuelve a intentarlo");
        }
            
    }//GEN-LAST:event_jBResolverActionPerformed
//Boton del menu de nueva partida, si quieres volver a jugar clicas y te manda a la pantalla principal otra vez
    private void jMINuvaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINuvaPartidaActionPerformed
        this.setVisible(false);
        PrimeraScreen nuevoJuego = null;
        nuevoJuego = new PrimeraScreen();
        nuevoJuego.setVisible(true);
    }//GEN-LAST:event_jMINuvaPartidaActionPerformed

    private void jCBAlejandroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBAlejandroMouseClicked
       //Le decimos que si esta seleccionado y clicamos se apaga y viceversa, para todos los checks box es igual.
        if(jCBAlejandro.isEnabled())
           jCBAlejandro.setEnabled(false);
       else
           jCBAlejandro.setEnabled(true);    
    }//GEN-LAST:event_jCBAlejandroMouseClicked

    private void JCBMariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBMariaActionPerformed
        //Tengo el raton roto y estos dos se me abrieron por la cara por que detecto un doble click y no se eliminarlos xD.
    }//GEN-LAST:event_JCBMariaActionPerformed

    private void jCBAlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlejandroActionPerformed

    }//GEN-LAST:event_jCBAlejandroActionPerformed

    private void JCBKikoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBKikoMouseClicked
        if(JCBKiko.isEnabled())
           JCBKiko.setEnabled(false);
       else
           JCBKiko.setEnabled(true);
    }//GEN-LAST:event_JCBKikoMouseClicked

    private void JCBJaviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBJaviMouseClicked
        if(JCBJavi.isEnabled())
           JCBJavi.setEnabled(false);
       else
           JCBJavi.setEnabled(true);
    }//GEN-LAST:event_JCBJaviMouseClicked

    private void JCBPepeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBPepeMouseClicked
        if(JCBPepe.isEnabled())
           JCBPepe.setEnabled(false);
       else
           JCBPepe.setEnabled(true);
    }//GEN-LAST:event_JCBPepeMouseClicked

    private void JCBMariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBMariaMouseClicked
        if(JCBMaria.isEnabled())
           JCBMaria.setEnabled(false);
       else
           JCBMaria.setEnabled(true);
    }//GEN-LAST:event_JCBMariaMouseClicked

    private void JCBIsabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBIsabelMouseClicked
        if(JCBIsabel.isEnabled())
           JCBIsabel.setEnabled(false);
       else
           JCBIsabel.setEnabled(true);
    }//GEN-LAST:event_JCBIsabelMouseClicked

    private void JCBCristinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBCristinaMouseClicked
        if(JCBCristina.isEnabled())
           JCBCristina.setEnabled(false);
       else
           JCBCristina.setEnabled(true);
    }//GEN-LAST:event_JCBCristinaMouseClicked

    private void JCBSusanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBSusanaMouseClicked
        if(JCBSusana.isEnabled())
           JCBSusana.setEnabled(false);
       else
           JCBSusana.setEnabled(true);
    }//GEN-LAST:event_JCBSusanaMouseClicked

    private void JCBAlfredoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBAlfredoMouseClicked
         if(JCBAlfredo.isEnabled())
           JCBAlfredo.setEnabled(false);
       else
           JCBAlfredo.setEnabled(true);
    }//GEN-LAST:event_JCBAlfredoMouseClicked

    private void JCBAlvaroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBAlvaroMouseClicked
        if(JCBAlvaro.isEnabled())
           JCBAlvaro.setEnabled(false);
       else
           JCBAlvaro.setEnabled(true);
    }//GEN-LAST:event_JCBAlvaroMouseClicked

    private void JCBAntonioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBAntonioMouseClicked
        if(JCBAntonio.isEnabled())
           JCBAntonio.setEnabled(false);
       else
           JCBAntonio.setEnabled(true);
    }//GEN-LAST:event_JCBAntonioMouseClicked

    private void JCBJoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBJoseMouseClicked
        if(JCBJose.isEnabled())
           JCBJose.setEnabled(false);
       else
           JCBJose.setEnabled(true);
    }//GEN-LAST:event_JCBJoseMouseClicked

    private void JCBJaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBJaviActionPerformed
        // Me fallo el raton aqui tambien.
    }//GEN-LAST:event_JCBJaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreenn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreenn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreenn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreenn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GameScreenn().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "Error entrada salida", ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GameScreenn.class.getName()).log(Level.SEVERE, "Error de clases", ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGPreguntas;
    private javax.swing.JCheckBox JCBAlfredo;
    private javax.swing.JCheckBox JCBAlvaro;
    private javax.swing.JCheckBox JCBAntonio;
    private javax.swing.JCheckBox JCBCristina;
    private javax.swing.JCheckBox JCBIsabel;
    private javax.swing.JCheckBox JCBJavi;
    private javax.swing.JCheckBox JCBJose;
    private javax.swing.JCheckBox JCBKiko;
    private javax.swing.JCheckBox JCBMaria;
    private javax.swing.JCheckBox JCBPepe;
    private javax.swing.JCheckBox JCBSusana;
    private javax.swing.JPanel PanlePrincipal;
    private javax.swing.JButton jBPreguntar;
    private javax.swing.JButton jBResolver;
    private javax.swing.JButton jBSalir;
    private javax.swing.JCheckBox jCBAlejandro;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JMenuItem jMINuvaPartida;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBotonesAccion;
    private javax.swing.JPanel jPanelDerecha;
    private javax.swing.JPanel jPanelInformacion;
    private javax.swing.JPanel jPanelJuego;
    private javax.swing.JPanel jPanelPersonajes;
    private javax.swing.JPanel jPanelPreguntas;
    private javax.swing.JRadioButton jRBigote;
    private javax.swing.JRadioButton jRBlanco;
    private javax.swing.JRadioButton jRCalvo;
    private javax.swing.JRadioButton jRHombre;
    private javax.swing.JRadioButton jRNarizon;
    private javax.swing.JRadioButton jRSombrero;
    // End of variables declaration//GEN-END:variables
}
